"""add is_admin flag to users

Revision ID: 457d01bbd7d2
Revises: 7e19f1675dde
Create Date: 2026-09-01 20:18:26.802461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457d01bbd7d2'
down_revision: Union[str, Sequence[str], None] = '7e19f1675dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )

    op.alter_column('users', 'is_admin', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
