(function () {
  "use strict";
  const { API, apiFetch, saveTokens, clearTokens, getAccessToken } = window.KairosAPI;
  const page = document.body.dataset.page || "landing";
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const escapeHtml = (value = "") => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char]));
  const empty = (title, message = "") => `<div class="empty-state"><strong>${escapeHtml(title)}</strong>${escapeHtml(message)}</div>`;
  const storedUser = () => { try { return JSON.parse(localStorage.getItem("kairos_user") || "{}"); } catch { return {}; } };
  const rowsOf = (value) => Array.isArray(value) ? value : [];
  const number = (value) => value === null || value === undefined || value === "" ? "—" : escapeHtml(value);
  const money = (value) => value === null || value === undefined || value === "" ? "—" : `₹${escapeHtml(value)}`;
  const date = (value) => { if (!value) return ""; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "" : parsed.toLocaleString(); };
  const initials = (name) => String(name || "K").trim().split(/\s+/).slice(0, 2).map((part) => part[0] || "").join("").toUpperCase();
  function toast(message, type = "") { const region = $("#toast-region"); if (!region) return; const item = document.createElement("div"); item.className = `toast ${type}`; item.textContent = message; region.appendChild(item); setTimeout(() => item.remove(), 4200); }
  function errorState(target, error) { target.className = "empty-state"; target.innerHTML = empty("Unable to load data", error.message); }
  function setupMenu() { const button = $(".menu-toggle"), nav = $(".desktop-nav"); if (!button || !nav) return; button.addEventListener("click", () => { const open = button.getAttribute("aria-expanded") === "true"; button.setAttribute("aria-expanded", String(!open)); nav.style.display = open ? "" : "grid"; nav.style.position = "absolute"; nav.style.top = "78px"; nav.style.left = "16px"; nav.style.right = "16px"; nav.style.padding = "16px"; nav.style.background = "#0B252A"; nav.style.border = "1px solid #123A40"; }); }
  function setupReveal() { $$(".reveal").forEach((el, i) => { el.style.animationDelay = `${Math.min(i * 45, 300)}ms`; }); }
  async function handleLogin(event) { event.preventDefault(); const form = event.currentTarget, error = $(".auth-error", form), button = $("button[type=submit]", form); error.style.display = "none"; button.disabled = true; button.textContent = "Signing in…"; try { const data = await apiFetch(API.auth.login, { method: "POST", body: JSON.stringify({ email: form.elements.email.value.trim(), password: form.elements.password.value }) }); saveTokens(data); const me = await apiFetch(API.users.me); localStorage.setItem("kairos_user", JSON.stringify(me)); location.href = "/pages/dashboard.html"; } catch (caught) { error.textContent = caught.message; error.style.display = "block"; } finally { button.disabled = false; button.textContent = "Log in"; } }
  async function handleRegister(event) { event.preventDefault(); const form = event.currentTarget, error = $(".auth-error", form), button = $("button[type=submit]", form); error.style.display = "none"; if (form.elements.password.value !== form.elements.confirm_password.value) { error.textContent = "Passwords do not match."; error.style.display = "block"; return; } button.disabled = true; button.textContent = "Creating your account…"; try { await apiFetch(API.auth.register, { method: "POST", body: JSON.stringify({ full_name: form.elements.full_name.value.trim(), username: form.elements.username.value.trim(), email: form.elements.email.value.trim(), password: form.elements.password.value, role: form.elements.role.value }) }); toast("Account created. Log in to continue.", "success"); setTimeout(() => { location.href = "/pages/login.html"; }, 700); } catch (caught) { error.textContent = caught.message; error.style.display = "block"; } finally { button.disabled = false; button.textContent = "Create account"; } }
  function setupAuth() { const login = $("#login-form"), register = $("#register-form"); if (login) login.addEventListener("submit", handleLogin); if (register) { register.addEventListener("submit", handleRegister); const role = new URLSearchParams(location.search).get("role"); if (["student", "mentor", "company"].includes(role)) { const input = $(`input[name=role][value=${role}]`); if (input) input.checked = true; } } $$(".password-toggle").forEach((button) => button.addEventListener("click", () => { const input = document.getElementById(button.dataset.target); input.type = input.type === "password" ? "text" : "password"; button.textContent = input.type === "password" ? "Show" : "Hide"; })); }
  function guard() { if (getAccessToken()) return true; location.href = "/pages/login.html?next=" + encodeURIComponent(location.pathname); return false; }
  const navItems = [{ href: "dashboard.html", label: "Overview", glyph: "⌂" }, { href: "profile.html", label: "My Profile", glyph: "◎" }, { href: "roadmap.html", label: "Roadmap", glyph: "↗" }, { href: "learning.html", label: "Learning", glyph: "◈" }, { href: "mentors.html", label: "Mentors", glyph: "♧" }, { href: "companies.html", label: "Companies", glyph: "▦" }, { href: "gigs.html", label: "Gigs", glyph: "✦" }, { href: "portfolio.html", label: "Portfolio", glyph: "⌁" }, { href: "resume.html", label: "Resume", glyph: "▤" }, { href: "notifications.html", label: "Notifications", glyph: "◌" }, { href: "wallet.html", label: "Wallet", glyph: "◒" }];
  function shell(title, subtitle, active) {
    const user = storedUser();
    const nav = navItems.map((item) => `<a class="${item.href === `${active}.html` ? "active" : ""}" href="/pages/${item.href}"><span class="nav-glyph">${item.glyph}</span>${item.label}${item.label === "Notifications" ? '<span class="nav-count" hidden></span>' : ""}</a>`).join("");
    document.body.className = "app-body";
    document.body.innerHTML = `<div id="toast-region" class="toast-region" aria-live="polite"></div><div class="app-shell"><aside class="app-sidebar" id="app-sidebar"><a class="brand-mark" href="/"><img src="/assets/images/kairos-logo.png" alt="Kairos" /></a><p class="sidebar-label">Your workspace</p><nav class="sidebar-nav" aria-label="App navigation">${nav}</nav><div class="sidebar-bottom"><a class="sidebar-nav" href="/pages/admin.html"><span class="nav-glyph">◫</span>Admin AI usage</a><div class="sidebar-profile"><span class="profile-avatar user-initials">${escapeHtml(initials(user.full_name))}</span><div><strong class="user-name">${escapeHtml(user.full_name || "Account")}</strong><small class="user-role">${escapeHtml(user.role || "")}</small></div><button class="icon-button logout-button" type="button" aria-label="Log out">↪</button></div></div></aside><main class="app-main"><div class="mobile-app-header"><button class="icon-button mobile-menu-button" type="button" aria-label="Open menu">☰</button><a class="brand-mark" href="/"><img src="/assets/images/kairos-logo.png" alt="Kairos" /></a><a class="icon-button" href="/pages/notifications.html">◌</a></div><header class="app-topbar"><div><p class="page-kicker">Kairos workspace</p><h1 class="page-title">${escapeHtml(title)}</h1><p class="page-subtitle">${escapeHtml(subtitle)}</p></div><div class="topbar-actions"><a class="icon-button" href="/pages/notifications.html" aria-label="Notifications">◌<span class="notification-dot" hidden></span></a><a class="profile-avatar user-initials" href="/pages/profile.html" aria-label="Open profile">${escapeHtml(initials(user.full_name))}</a></div></header><div class="app-content" id="page-content"></div></main></div>`;
    $(".logout-button").addEventListener("click", () => { clearTokens(); location.href = "/"; });
    $(".mobile-menu-button").addEventListener("click", () => $("#app-sidebar").classList.toggle("open"));
    apiFetch(API.users.me).then((fresh) => { localStorage.setItem("kairos_user", JSON.stringify(fresh)); $$(".user-initials").forEach((el) => { el.textContent = initials(fresh.full_name); }); $(".user-name").textContent = fresh.full_name || "Account"; $(".user-role").textContent = fresh.role || ""; if (page === "dashboard") $(".page-title").textContent = fresh.full_name ? `Good morning, ${fresh.full_name.split(" ")[0]}` : "Good morning"; }).catch(() => {});
    updateNotificationCount();
    return $("#page-content");
  }
  async function updateNotificationCount() { try { const rows = rowsOf(await apiFetch(API.notifications.list)); const count = rows.filter((row) => row.is_read === false).length; const chip = $(".nav-count"), dot = $(".notification-dot"); if (chip) { chip.hidden = count === 0; chip.textContent = String(count); } if (dot) dot.hidden = count === 0; } catch { const chip = $(".nav-count"), dot = $(".notification-dot"); if (chip) chip.hidden = true; if (dot) dot.hidden = true; } }
  function notificationMarkup(row) { return `<div class="timeline-item"><span class="timeline-dot"></span><div><strong>${escapeHtml(row.message || "Notification")}</strong>${row.created_at ? `<p>${escapeHtml(date(row.created_at))}</p>` : ""}</div></div>`; }
  function badgeMarkup(badge) { return `<span class="skill-badge"><span aria-hidden="true">✦</span>${escapeHtml(badge.skill_name)}</span>`; }
  async function renderDashboard() {
    if (!guard()) return;
    const user = storedUser();
    const root = shell(user.full_name ? `Good morning, ${user.full_name.split(" ")[0]}` : "Good morning", "Your actual workspace activity.", "dashboard");
    root.innerHTML = `<section class="welcome-panel"><div><span class="welcome-tag" id="today"></span><h2>Your next move starts here.</h2><p>Explore your roadmap, verified skills and recent updates.</p></div><a class="button button-gold" href="/pages/roadmap.html">View roadmap <span>↗</span></a></section><section class="metric-grid" id="dashboard-metrics"></section><section class="dashboard-grid"><article class="panel"><div class="panel-header"><h3 class="panel-title">Your roadmap</h3><a class="panel-link" href="/pages/roadmap.html">Open roadmap →</a></div><div id="dashboard-roadmap">${empty("No roadmap loaded", "Generate a roadmap on the Roadmap page. This API does not provide a list of your existing roadmaps.")}</div></article><article class="panel"><div class="panel-header"><h3 class="panel-title">Recent notifications</h3><a class="panel-link" href="/pages/notifications.html">See all →</a></div><div id="dashboard-notifications">${empty("Loading notifications…")}</div></article></section><section class="panel"><div class="panel-header"><h3 class="panel-title">Your verified skills</h3><a class="panel-link" href="/pages/learning.html">Explore learning →</a></div><div id="dashboard-badges">${empty("Loading badges…")}</div></section><section><div class="panel-header"><h3 class="panel-title">Explore</h3></div><div class="quick-actions"><a class="quick-action" href="/pages/roadmap.html"><span>↗</span><strong>Roadmap</strong></a><a class="quick-action" href="/pages/mentors.html"><span>♧</span><strong>Find a mentor</strong></a><a class="quick-action" href="/pages/portfolio.html"><span>⌁</span><strong>Portfolio</strong></a></div></section>`;
    $("#today").textContent = new Intl.DateTimeFormat(undefined, { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date());
    const metrics = $("#dashboard-metrics");
    metrics.innerHTML = `<article class="metric-card"><span class="metric-label">Verified badges</span><strong class="metric-value" id="dashboard-badge-count">—</strong></article><article class="metric-card"><span class="metric-label">Portfolio items</span><strong class="metric-value" id="dashboard-portfolio-count">—</strong></article><article class="metric-card"><span class="metric-label">Unread notifications</span><strong class="metric-value" id="dashboard-unread-count">—</strong></article>`;
    const jobs = [
      apiFetch(API.learning.badges).then((data) => { const badges = rowsOf(data).filter((badge) => badge.status === "verified"); $("#dashboard-badge-count").textContent = badges.length; $("#dashboard-badges").innerHTML = badges.length ? (badges.every((badge) => badge.skill_name) ? `<div class="badge-row">${badges.map(badgeMarkup).join("")}</div>` : empty("Skill names unavailable", "The badge API returned IDs without skill names. Update the backend API and verify which API URL this site is using.")) : empty("No verified badges yet"); }).catch((err) => { $("#dashboard-badges").innerHTML = empty("Unable to load badges", err.message); }),
      apiFetch(API.companies.portfolio).then((data) => { $("#dashboard-portfolio-count").textContent = rowsOf(data?.items).length; }).catch(() => {}),
      apiFetch(API.notifications.list).then((data) => { const rows = rowsOf(data); $("#dashboard-unread-count").textContent = rows.filter((row) => row.is_read === false).length; $("#dashboard-notifications").innerHTML = rows.length ? `<div class="timeline-list">${rows.slice(0, 3).map(notificationMarkup).join("")}</div>` : empty("No notifications yet"); }).catch((err) => { $("#dashboard-notifications").innerHTML = empty("Unable to load notifications", err.message); })
    ];
    await Promise.allSettled(jobs);
  }
  async function renderProfile() {
    if (!guard()) return;
    const root = shell("My profile", "Update the information used for your account.", "profile");
    root.innerHTML = `<div class="form-card"><form id="profile-form" class="form-grid"><div class="form-field"><label for="college">College</label><input id="college" name="college" placeholder="Your college or university" /></div><div class="form-field"><label for="degree">Degree</label><input id="degree" name="degree" placeholder="Your degree" /></div><div class="form-field"><label for="year">Year</label><input id="year" name="year" placeholder="Year of study" /></div><div class="form-field"><label for="country">Country</label><input id="country" name="country" placeholder="Where are you based?" /></div><div class="form-field full"><label for="bio">Bio</label><textarea id="bio" name="bio" placeholder="Tell us about yourself"></textarea></div><div class="form-actions full"><button class="button button-gold" type="submit">Save profile <span>↗</span></button></div></form></div><div class="panel"><div class="panel-header"><h3 class="panel-title">Skill assessment</h3></div><form id="assessment-form" class="form-grid"><div class="form-field"><label for="skill_level">Current level</label><select id="skill_level" name="skill_level"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></div><div class="form-field"><label for="time_available">Time available</label><input id="time_available" name="time_available" placeholder="Hours per week" /></div><div class="form-field full"><label for="known_languages">Known languages</label><input id="known_languages" name="known_languages" placeholder="Languages you know" /></div><div class="form-field full"><label for="career_goal">Career goal</label><textarea id="career_goal" name="career_goal" placeholder="What would you like to do next?"></textarea></div><div class="form-actions full"><button class="button button-outline" type="submit">Save assessment</button></div></form></div>`;
    try { const profile = await apiFetch(API.users.profile); ["college", "degree", "year", "country", "bio", "skill_level", "known_languages", "time_available", "career_goal"].forEach((key) => { const input = document.getElementById(key); if (input && profile?.[key] != null) input.value = profile[key]; }); } catch (error) { toast(error.message, "error"); }
    $("#profile-form").addEventListener("submit", async (event) => { event.preventDefault(); try { await apiFetch(API.users.profile, { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); toast("Profile updated.", "success"); } catch (error) { toast(error.message, "error"); } });
    $("#assessment-form").addEventListener("submit", async (event) => { event.preventDefault(); try { await apiFetch(API.users.assessment, { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); toast("Assessment saved.", "success"); } catch (error) { toast(error.message, "error"); } });
  }
  async function loadInto(selector, endpoint, render, loading = "Loading…") { const target = $(selector); target.className = "empty-state"; target.innerHTML = empty(loading); try { const data = await apiFetch(endpoint); render(target, data); } catch (error) { errorState(target, error); } }
  function renderRoadmap(root) {
    root.innerHTML = `<div class="panel"><div class="panel-header"><h3 class="panel-title">Generate your roadmap</h3></div><form id="roadmap-form" class="form-grid"><div class="form-field"><label for="interest">Interest</label><select id="interest" name="interest"><option>Web Development</option><option>AI</option><option>UI/UX</option><option>Data Science</option><option>Cyber Security</option><option>Cloud</option></select></div><div class="form-field"><label for="roadmap-level">Skill level</label><select id="roadmap-level" name="skill_level"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></div><div class="form-field"><label for="weeks">Duration</label><select id="weeks" name="weeks"><option value="8">8 weeks</option><option value="12" selected>12 weeks</option><option value="16">16 weeks</option></select></div><div class="form-field"><label for="career_goal">Career goal</label><input id="career_goal" name="career_goal" placeholder="Your career goal" /></div><div class="form-actions full"><button class="button button-gold" type="submit">Generate roadmap <span>↗</span></button></div></form></div><div class="panel"><div class="panel-header"><h3 class="panel-title">Roadmap timeline</h3></div><div id="roadmap-result">${empty("No roadmap loaded", "Generate a roadmap to view its timeline. Existing roadmaps cannot be listed by the current API.")}</div></div>`;
    $("#roadmap-form").addEventListener("submit", async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); data.weeks = Number(data.weeks); const target = $("#roadmap-result"); target.innerHTML = empty("Submitting roadmap request…"); try { const accepted = await apiFetch(API.roadmaps.generate, { method: "POST", body: JSON.stringify(data) }); if (!accepted?.roadmap_id) throw new Error("No roadmap ID returned."); target.innerHTML = empty("Generating your roadmap…"); for (let attempt = 0; attempt < 20; attempt++) { await new Promise((resolve) => setTimeout(resolve, 1600)); const result = await apiFetch(API.roadmaps.detail(accepted.roadmap_id)); if (result.status === "generating") continue; if (result.status !== "ready") { target.innerHTML = empty("Roadmap generation did not complete", `Status: ${result.status || "unknown"}`); return; } const rows = rowsOf(result.items); target.innerHTML = rows.length ? `<div class="timeline-list">${rows.map((item) => `<div class="timeline-item"><span class="timeline-dot"></span><div><strong>Week ${number(item.week_number)} · ${escapeHtml(item.title)}</strong><p>${escapeHtml(item.description || "")}${item.estimated_hours != null ? ` · ${number(item.estimated_hours)} hours` : ""}</p></div></div>`).join("")}</div>` : empty("Roadmap is ready but has no items"); return; } target.innerHTML = empty("Still generating", "The request is taking longer than expected. The current API does not list previously generated roadmaps."); } catch (error) { target.innerHTML = empty("Unable to generate roadmap", error.message); } });
  }
  function renderLearning(root) { root.innerHTML = `<div class="panel"><div class="panel-header"><h3 class="panel-title">Verified skill badges</h3><button class="button button-outline" id="load-badges" type="button">Refresh</button></div><div id="badge-results">${empty("Loading badges…")}</div></div><div class="panel">${empty("Learning modules unavailable", "The current API has no endpoint for listing your modules, quiz attempts or project submissions.")}</div>`; const load = () => loadInto("#badge-results", API.learning.badges, (target, data) => { const badges = rowsOf(data).filter((badge) => badge.status === "verified"); target.className = badges.length ? "badge-row" : "empty-state"; target.innerHTML = badges.length ? (badges.every((badge) => badge.skill_name) ? badges.map(badgeMarkup).join("") : empty("Skill names unavailable", "The badge API returned IDs without skill names. Update the backend API and verify which API URL this site is using.")) : empty("No verified badges yet"); }, "Loading badges…"); $("#load-badges").addEventListener("click", load); load(); }
  function renderMentors(root) { root.innerHTML = `<div class="panel"><div class="panel-header"><h3 class="panel-title">Mentor directory</h3><button class="button button-outline" id="load-mentors" type="button">Refresh directory</button></div><div id="mentor-results">${empty("Loading mentors…")}</div></div>`; const load = () => loadInto("#mentor-results", API.mentors.list, (target, data) => { const rows = rowsOf(data); target.className = rows.length ? "role-grid" : "empty-state"; target.innerHTML = rows.length ? rows.map((m) => `<article class="role-card"><div><span class="role-number">${m.is_available ? "AVAILABLE" : "UNAVAILABLE"}</span><h3>${escapeHtml(m.domain || "Mentor")}</h3><p>${m.experience_years != null ? `${number(m.experience_years)} years experience` : "Experience not provided"}${m.rating != null ? ` · ★ ${number(m.rating)}` : ""}</p></div><a class="button button-gold" href="/pages/mentor-detail.html?id=${encodeURIComponent(m.id)}">View mentor <span>↗</span></a></article>`).join("") : empty("No mentors found"); }, "Loading mentors…"); $("#load-mentors").addEventListener("click", load); load(); }
  function renderCompanies(root) { root.innerHTML = `<div class="panel"><div class="panel-header"><h3 class="panel-title">Open roles</h3><button class="button button-outline" id="load-jobs" type="button">Refresh jobs</button></div><div id="job-results">${empty("Loading jobs…")}</div></div>`; const load = () => loadInto("#job-results", API.companies.jobs, (target, data) => { const rows = rowsOf(data); target.className = rows.length ? "table-wrap" : "empty-state"; target.innerHTML = rows.length ? `<table><thead><tr><th>Role</th><th>Status</th><th>Budget</th><th>Action</th></tr></thead><tbody>${rows.map((job) => `<tr><td><strong>${escapeHtml(job.title)}</strong>${job.description ? `<br /><span class="muted">${escapeHtml(job.description)}</span>` : ""}</td><td>${escapeHtml(job.status || "—")}</td><td>${money(job.budget)}</td><td><button class="button button-outline job-apply" type="button" data-id="${escapeHtml(job.id)}">Apply</button></td></tr>`).join("")}</tbody></table>` : empty("No open roles yet"); }, "Loading jobs…"); $("#load-jobs").addEventListener("click", load); $("#job-results").addEventListener("click", async (event) => { const button = event.target.closest(".job-apply"); if (!button || button.disabled) return; if (!window.confirm("Apply to this job now?")) return; button.disabled = true; try { await apiFetch(API.companies.apply(button.dataset.id), { method: "POST" }); toast("Application submitted.", "success"); } catch (error) { toast(error.message, "error"); } finally { button.disabled = false; } }); load(); }
  function renderGigs(root) { root.innerHTML = `<div class="panel"><div class="panel-header"><h3 class="panel-title">Eligible gigs</h3><button class="button button-outline" id="load-gigs" type="button">Load eligible gigs</button></div><div id="gig-results">${empty("Loading eligible gigs…")}</div></div>`; const load = () => loadInto("#gig-results", API.gigs.list, (target, data) => { const rows = rowsOf(data); target.className = rows.length ? "role-grid" : "empty-state"; target.innerHTML = rows.length ? rows.map((gig) => `<article class="metric-card"><span class="metric-label">${escapeHtml(gig.difficulty || "Gig")}</span><strong>${escapeHtml(gig.title)}</strong>${gig.description ? `<p class="muted">${escapeHtml(gig.description)}</p>` : ""}<span class="metric-change">${money(gig.budget)}</span><p><a class="button button-outline" href="/pages/gig-detail.html?id=${encodeURIComponent(gig.id)}">View details</a></p></article>`).join("") : empty("No eligible gigs found"); }, "Loading eligible gigs…"); $("#load-gigs").addEventListener("click", load); load(); }
  function renderPortfolio(root) { root.innerHTML = `<div class="panel"><div class="panel-header"><h3 class="panel-title">Your portfolio</h3><button class="button button-outline" id="load-portfolio" type="button">Refresh</button></div><div id="portfolio-results">${empty("Loading portfolio…")}</div></div>`; const load = () => loadInto("#portfolio-results", API.companies.portfolio, (target, data) => { const rows = rowsOf(data?.items); target.className = rows.length ? "table-wrap" : "empty-state"; target.innerHTML = rows.length ? `<table><thead><tr><th>Project</th><th>Source</th><th>Rating</th></tr></thead><tbody>${rows.map((item) => `<tr><td><strong>${escapeHtml(item.title)}</strong>${item.description ? `<br /><span class="muted">${escapeHtml(item.description)}</span>` : ""}</td><td>${escapeHtml(item.source_type || "—")}</td><td>${number(item.rating)}</td></tr>`).join("")}</tbody></table>` : empty("No portfolio items yet"); }, "Loading portfolio…"); $("#load-portfolio").addEventListener("click", load); load(); }
  function renderResume(root) { root.innerHTML = `<div class="panel"><div class="panel-header"><h3 class="panel-title">Generate a resume preview</h3></div><form id="resume-form" class="form-grid"><div class="form-field"><label for="template">Template</label><select id="template" name="template"><option value="standard">Standard</option><option value="modern">Modern</option><option value="minimal">Minimal</option></select></div><div class="form-actions"><button class="button button-gold" type="submit">Generate preview <span>↗</span></button></div></form><pre id="resume-preview" class="resume-preview"></pre></div>`; $("#resume-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const data = await apiFetch(API.companies.resume, { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); $("#resume-preview").textContent = data?.content_preview || "No resume content returned."; } catch (error) { toast(error.message, "error"); } }); }
  function renderNotifications(root) { root.innerHTML = `<div class="panel"><div class="panel-header"><h3 class="panel-title">Your updates</h3><button class="button button-outline" id="load-notifications" type="button">Refresh</button></div><div id="notification-results">${empty("Loading notifications…")}</div></div>`; const load = () => loadInto("#notification-results", API.notifications.list, (target, data) => { const rows = rowsOf(data); target.className = rows.length ? "timeline-list" : "empty-state"; target.innerHTML = rows.length ? rows.map(notificationMarkup).join("") : empty("No notifications yet"); updateNotificationCount(); }, "Loading notifications…"); $("#load-notifications").addEventListener("click", load); load(); }
  function renderWallet(root) { root.innerHTML = `<div class="metric-grid"><article class="metric-card"><span class="metric-label">Available balance</span><strong class="metric-value" id="available-balance">—</strong></article><article class="metric-card"><span class="metric-label">Pending balance</span><strong class="metric-value" id="pending-balance">—</strong></article></div><div class="panel"><div class="panel-header"><h3 class="panel-title">Payment history</h3></div><div id="wallet-results">${empty("Loading payments…")}</div></div>`; apiFetch(API.payments.wallet).then((wallet) => { $("#available-balance").textContent = money(wallet.balance); $("#pending-balance").textContent = money(wallet.pending_balance); }).catch((error) => toast(error.message, "error")); loadInto("#wallet-results", API.payments.history, (target, data) => { const rows = rowsOf(data); target.className = rows.length ? "table-wrap" : "empty-state"; target.innerHTML = rows.length ? `<table><thead><tr><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>${rows.map((item) => `<tr><td>${money(item.amount)}</td><td>${escapeHtml(item.status || "—")}</td><td>${escapeHtml(date(item.created_at) || "—")}</td></tr>`).join("")}</tbody></table>` : empty("No payments yet"); }, "Loading payments…"); }
  function renderAdmin(root) { root.innerHTML = `<div class="panel"><div class="panel-header"><h3 class="panel-title">AI usage</h3><button class="button button-outline" id="load-usage" type="button">Refresh metrics</button></div><div id="usage-results">${empty("Loading usage…")}</div></div>`; const load = () => loadInto("#usage-results", API.admin.usage, (target, usage) => { target.className = "metric-grid"; target.innerHTML = Object.entries({ "Calls today": usage.calls_today, "Soft limit": usage.soft_limit, "Remaining": usage.remaining_before_soft_block, "Resets in": usage.resets_in_seconds == null ? null : `${Math.round(usage.resets_in_seconds / 3600)}h` }).map(([label, value]) => `<article class="metric-card"><span class="metric-label">${label}</span><strong class="metric-value">${number(value)}</strong></article>`).join(""); }, "Loading usage…"); $("#load-usage").addEventListener("click", load); load(); }
  function renderFeaturePage() { if (!guard()) return; const titles = { roadmap: ["Roadmap", "Generate a plan for your goals."], learning: ["Learning", "View your verified badges."], mentors: ["Mentors", "Find mentors in the directory."], companies: ["Companies & jobs", "Browse open roles."], gigs: ["Gig marketplace", "Browse opportunities matching your badges."], portfolio: ["Portfolio", "See your work."], resume: ["Resume studio", "Generate a resume from your profile and portfolio."], notifications: ["Notifications", "Your account updates."], wallet: ["Wallet", "Your balances and payments."], admin: ["AI usage", "Admin-only usage metrics."] }; const [title, subtitle] = titles[page]; const root = shell(title, subtitle, page); ({ roadmap: renderRoadmap, learning: renderLearning, mentors: renderMentors, companies: renderCompanies, gigs: renderGigs, portfolio: renderPortfolio, resume: renderResume, notifications: renderNotifications, wallet: renderWallet, admin: renderAdmin })[page](root); }
  function boot() { setupMenu(); setupReveal(); if (page === "login" || page === "register") setupAuth(); else if (page === "dashboard") renderDashboard(); else if (page === "profile") renderProfile(); else if (["roadmap", "learning", "mentors", "companies", "gigs", "portfolio", "resume", "notifications", "wallet", "admin"].includes(page)) renderFeaturePage(); }
  boot();
})();
